name: "Build legacy Nix package on Ubuntu"

on:
  push:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v12
      - name: Building package
        run: nix-build . -A defaultPackage.x86_64-linux
