name: EmCMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Setup env"
        uses: JRMurr/direnv-nix-action@v4.1.0

      - name: use node
        run: emcc --version
        shell: bash
