name: EmCMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        shell: bash
        run: |
          nix develop
          emcmake cmake --preset emscripten-release
          cmake --build build/emscripten-release

      - name: Copy build
        shell: bash
        run: |
          rsync -r --checksum  build/emscripten-release/* /var/lib/www/engine.rlyeh.nu
