name: EmCMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        shell: bash
        run: |
          nix develop -c cmake --preset emscripten-debug
          nix develop -c cmake --build build/emscripten-debug

      - name: Copy build
        shell: bash
        run: |
          rsync -r --checksum  build/emscripten-debug/* /var/lib/www/engine.rlyeh.nu
