name: EmCMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        shell: bash
        run: |
          /run/current-system/sw/bin/direnv allow && echo "use nix"
          eval "$(/run/current-system/sw/bin/direnv export bash)"
          emcmake cmake --preset emscripten-release
          EM_CACHE=~/.emscripten_cache cmake --build build/emscripten-release

      - name: Copy build
        shell: bash
        run: |
          rsync -r --checksum  build/emscripten-release/* /var/lib/www/engine.rlyeh.nu
