name: CMake Build on NixOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Build with Nix
      run: |
        nix --experimental-features "nix-command flakes" develop -c cmake -S . -B build
        nix --experimental-features "nix-command flakes" develop -c cmake --build build
